### ISSUE TITLE
Does not support comments in PromQL

### ISSUE THREAD

**Issue by M3t0r** [facetoe/promformat#11]
https://prometheus.io/docs/prometheus/latest/querying/basics/#comments

    $ cat > test.promql <<EOQ
    series_name{
        label="matching" # for testing
    }
    EOQ
    $ promformat test.promql 
    line 2:21 token recognition error at: '#'
    line 2:23 no viable alternative at input 'series_name{label="matching"for'
    visitVector
    Traceback (most recent call last):
      File "/usr/bin/promformat", line 33, in <module>
        sys.exit(load_entry_point('promformat==0.0.4', 'console_scripts', 'promformat')())
      File "/usr/lib/python3.10/site-packages/promformat/__main__.py", line 19, in main
        result = format_query(query)
      File "/usr/lib/python3.10/site-packages/promformat/__init__.py", line 18, in format_query
        formatted_promql = formatter.format(abstract_syntax_tree)
      File "/usr/lib/python3.10/site-packages/promformat/formatter.py", line 383, in format
        self.visit(tree)
      File "/usr/lib/python3.10/site-packages/promformat/formatter.py", line 388, in visit
        method = self.__getattribute__(method_name)
    AttributeError: 'PromQLFormatter' object has no attribute 'visitNoneType'

For comparison, the same query without comment:

    $ cat > test.promql <<EOQ
    series_name{        
        label="matching"
    }  
    EOQ
    $ promformat test.promql
    series_name
    {
      label="matching"
    }

**Comment by facetoe** [comment]
It would be great to support comments. Probably they need to be added to the antlr4 grammar first.
